/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guc_kotlinframe_jni_HelloJni */

#ifndef _Included_com_guc_kotlinframe_jni_HelloJni
#define _Included_com_guc_kotlinframe_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guc_kotlinframe_jni_HelloJni
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guc_kotlinframe_jni_HelloJni_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
